name: Slack Notification

on:
  pull_request:
    branches: [ "dev", "main" ]
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set PR name
        id: pr_name
        run: echo "::set-output name=pr_name::$(echo ${{ github.event.pull_request.title }})"

      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          text: ${{ steps.pr_name.outputs.pr_name }}
          status: ${{ job.status }}
          author_name: |
            Branch: ${{ github.base_ref }}
          mention: ${{ secrets.BACKEND_SLACK_USERID }}
          if_mention: always
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_PR }}
        if: always()